### PR TITLE
ES6 -> ES5

### PR DESCRIPTION
**Pull request by vihanb**
transpiled but I haven't tested if this works. I also had to change `mathC[6] = eval` to `mathC[6] = _eval`

### CODE REVIEW

**Comment by RikerW** [comment]
Try testing it.

**Comment by ConorOBrien-Foxx** [comment]
_has conflicts._

**Comment by phase** [comment]
That's when you merge on the command line.

**Comment by ConorOBrien-Foxx** [comment]
¯_(ツ)_/¯ Don't know how to use the command line, and I don't care.

**Comment by vihanb** [comment]
ಠ_ಠ

**Comment by phase** [comment]
```
$ git fetch origin pull/7/head:es5
$ git checkout es5
$ git merge master -X ours
$ git push origin master
```

Now you know how to do it and I shall call you lazy for not doing so.

(_not actually sure if that works_)

**Comment by ConorOBrien-Foxx** [comment]
I don't know what this is because I'm a filthy windows user

**Comment by phase** [comment]
Git is literally on every platform, and has been for years.

**Comment by ConorOBrien-Foxx** [comment]
To much jQuery (`$`)

**Comment by vihanb** [comment]
ಠ_ಠ

**Comment by phase** [comment]
*_too_
and _wat_

**Comment by ConorOBrien-Foxx** [comment]
naw, I meant to.

**Pull request closed without merging**
